### ISSUE TITLE
Provide a new documentation template for our components

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus#113]
**Is your feature request related to a problem? Please describe.**
Provide a new documentation template for our components that is more user-friendly and easier to find our content.

**Describe the solution you'd like**
Things that would be good to have:
- Sidebar navigation
- Search

## Scope

- [x] https://azure-ml.arcus-azure.net/
- [x] https://background-jobs.arcus-azure.net/
- [x] https://eventgrid-proxy.arcus-azure.net/
- [x] https://eventgrid.arcus-azure.net/
- [x] https://messaging.arcus-azure.net/
- [x] https://machine-learning.arcus-azure.net/
- [x] https://observability.arcus-azure.net/
- [x] https://scripting.arcus-azure.net/
- [x] https://security.arcus-azure.net/
- [x] https://templates.arcus-azure.net/
- [x] https://webapi.arcus-azure.net/
- [x] Prepare our GitHub repo template (https://github.com/arcus-azure/arcus.github.template)

## Tasklist

- Apply new template
- Change Netlify site name to no longer state `-preview`
- Change Netlify to no longer serve `Preview Notice` banner
- Change Netlify to serve from custom domain
- Change Netlify to use latest Git repo (triggers new GitHub integration)
- Change branch policies to enforce new site name
- Change DNS entry in CloudFlare
- Disable GitHub pages

**Comment by tomkerkhove** [comment]
Prototype: https://arcus-security-refresh.netlify.app/

**Comment by tomkerkhove** [comment]
We will use https://www.docsy.dev/docs/examples/ with Hugo instead of Jekyll

**Comment by tomkerkhove** [comment]
@Mcalewaert will work on this

**Comment by tomkerkhove** [comment]
@Mcalewaert do we have to do something with regards to the search?

**Comment by Mcalewaert** [comment]
@tomkerkhove I've requested the indexing of the documentation websites that were already deployed yesterday. Have to make some more requests for the ones that were merged and deployed today. But this can take a while since they have to manually approve everyone's request.

**Comment by tomkerkhove** [comment]
Thank you!

**Comment by tomkerkhove** [comment]
I think that's it - Thanks a ton!
