### ISSUE TITLE
Provide guidance on automated checks for code styling & conventions

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus#12]
Provide guidance on automated checks for code styling & conventions.

It should cover the following topics:
- What tool do we use?
- How do we enforce this in the CI?
- How do I get up & running?

A new issue should be created for every new repo that is setup with our tooling.

Options are:

- Resharper Code Quality
- .NET / VS tooling
- StyleCop

Suggestions are welcome in the comments!

**Comment by samneirinck** [comment]
I like .editorconfig, but there's no compiler support yet (https://github.com/dotnet/roslyn/projects/18)

**Comment by tomkerkhove** [comment]
Looks like www.codefactor.io is free, automatically integrates with PRs and uses StyleCop which is also free.

Maybe good to give this one a spin?

**Comment by samneirinck** [comment]
Is stylecop still up to date/relevant in the .NET core era? Can always try and see how it works out I guess.

**Comment by tomkerkhove** [comment]
Configured this for Promitor, feel free to have a look - https://www.codefactor.io/repository/github/tomkerkhove/promitor

I think it is but I'm not an expert on the topic. As long as .editorconfig doesn't have compiler support it doesn't make sense to me. We could also use Resharper but that forces people to pay for it in order to contribute which is not great.

**Comment by samneirinck** [comment]
Ok, as long as it's integrated into the local build, I'm fine with it.

The benefit is a nice UI I suppose? Because if you're already using the analyzer, it's integrated in the compilation, and provides warnings/errors right there.

**Comment by tomkerkhove** [comment]
Adding @fgheysels as he might have some input on htis

**Comment by fgheysels** [comment]
I've no experience with codefactor.   I agree with Sam that the style-checking should be applied when building locally as well, and Stylecop can do that.  (I suggest to customize the Stylecop ruleset though, since I'm sure that there are rules were we do not agree on).

Since codefactor uses Stylecop, what else does it bring to the table ? What is the added value of codefactor as opposed to only using stylecop ?

**Comment by tomkerkhove** [comment]
Stylecop is ok for me to be honest, just turned on Codefactor for [Promitor](https://www.codefactor.io/repository/github/tomkerkhove/promitor) and that did the trick for me and didn't do the effort to customize Stylecop but would give local experience as well.

I see Codefactor just as an extension of Stylecop where it gives UI & PR checks, but those can also be done via build ofcourse. It's not a must, was just a suggestion.

The alternative would be .editorconfig, however, but I don't think it's good enough yet for our scenario.

So shall we decide to use Stylecop going forward?

**Comment by samneirinck** [comment]
Yes 👌

**Comment by stijnmoreels** [comment]
Added Codefactor to the repo's but didn't add yet a custom set of rules.
