### ISSUE TITLE
[Blog] Write blog post on the new v1.3.0 web API package

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#132]
**What is the goal of the blog post**
We have a lot of new features in the v1.3.0 release and we should describe them more fluently in a blog post.

**Describe the post outline you'd like**
It's all about request tracking: omitting request routes, status code allow list, exclude request/response bodies...

**Additional context**
https://github.com/arcus-azure/arcus.webapi/releases/tag/v1.3.0

**Comment by stijnmoreels** [comment]
Let's keep it open until it's published.

**Comment by tomkerkhove** [comment]
They cannot keep up with your speed, Stijn!

**Comment by stijnmoreels** [comment]
> They cannot keep up with your speed, Stijn!

😅 You have a point there ☺️
I'm planning on writing further on the blog post for the advantages of the secret store.

**Comment by stijnmoreels** [comment]
Published: https://www.codit.eu/blog/enhanced-request-tracking-in-arcus-web-api-v1-3/ 🎉
