### ISSUE TITLE
Use alternative for obsolete NuGet license and package URL

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#134]
**Is your feature request related to a problem? Please describe.**
Currently, we use obsolete icon and package URL NuGet packaging options, which could be removed in the future.

**Describe the solution you'd like**
A more better approach would be, when this is in fact removed, that we use the icon file itself and use a license alias.

**Additional context**
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5048
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5125

**Comment by tomkerkhove** [comment]
What  do you mean with license alias? Can we add the license file to the package itself?

We might want to add our README as part of the package if not already.

https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/

**Comment by stijnmoreels** [comment]
> What do you mean with license alias? 
Yeah, I meant the license expression 
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file

> Can we add the license file to the package itself?
We can, but it's gonna be harder to change something in the license then maybe bc we have to change it then in every repo ...
