### ISSUE TITLE
Migrate to new ubuntu environment in build pipelines

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#144]
**Is your feature request related to a problem? Please describe.**
This September, our ubuntu TLS deprecated version 16.04 will be removed.

**Describe the solution you'd like**
We should move our pipelines to 18.04.

**Additional context**
https://github.com/actions/virtual-environments/issues/3287

**Comment by tomkerkhove** [comment]
Aren't we using `ubuntu-latest`? If not, we should.

**Comment by stijnmoreels** [comment]
> Aren't we using `ubuntu-latest`? If not, we should.

No, we're using 16.04 everywhere. Ok, latest? So we're future-proof, maybe?

**Comment by tomkerkhove** [comment]
Yes because we basically don't care what Linux version, as long as it is Linux.
