### ISSUE TITLE
Rename `master` to `main` to be universally comfortable

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#169]
**Is your feature request related to a problem? Please describe.**
We are still using the old `master`/`slave` way of naming our branches.

**Describe the solution you'd like**
We should consider renaming to `main` to make it universally comfortable for everyone.

**Comment by fgheysels** [comment]
How does this affect forks ?

**Comment by stijnmoreels** [comment]
> How does this affect forked repositories ?

We will have to rename locally our branches, and change the default branch. And changing the upstream. There are a lot of tutorials for this.
For example: https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/

**Comment by stijnmoreels** [comment]
I think we're done here 💃
