### ISSUE TITLE
[Docs] Add 'Why should I use Arcus?' section to site

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#173]
**What is the goal of the documentation**
We should come up with a list that we can add to the general Arcus website that explains why people should use Arcus.

**How do you think this will help?**
People will get a more clear understanding on Arcus and hopefully adopt it in their projects more.

**Comment by stijnmoreels** [comment]
- [ ] It helps you setting up certain infrastructure (it saves you time)
- [ ] it avoids repeating the same code over and over on each project, or having to copy/paste code from past projects (which might already be outdated). It prevents you from building your own library for these kind of things (and Arcus is well-tested)
- [ ] Security and observability out-of-the-box. Telemetry by-default present in any Arcus functionality, security events, usage of secret store by-default

**Comment by pim-simons** [comment]
This is a good starting point I think: https://security.arcus-azure.net/features/secret-store/#why-would-i-use-it

**Comment by fgheysels** [comment]
As said, I think we should have some global advantages, not related to a repo.  Next to that, we can create a page similar to what @pim-simons  mentions for every Arcus repository with specific advantages for that repo.

**Comment by pim-simons** [comment]
> As said, I think we should have some global advantages, not related to a repo. Next to that, we can create a page similar to what @pim-simons mentions for every Arcus repository with specific advantages for that repo.

Sounds great 👍🏻

**Comment by Dirk-Luyckx** [comment]
> As said, I think we should have some global advantages, not related to a repo. Next to that, we can create a page similar to what @pim-simons mentions for every Arcus repository with specific advantages for that repo.

Agree! There even is a level above - advantages of using Arcus across projects, where this can help that across different Codit projects we do things in the same way; helping out towards colleagues working on multiple projects and shifting projects; and also towards Managed Services. 
Having said that, this is not something I think we need to take to benefits of Arcus as an initiative, but does offer extra incentive to have broader adoption within Codit.

**Comment by stijnmoreels** [comment]
Once we come up with the final points, we can maybe ask our cool frontend team to help us to include this in the page. Maybe we need some icons or vectors for each point and seemed like a good thing to outsource this to people with more design brains 😅 .

From the things described here, this is the first draft:
✔ **Time-saving**: it helps you setting up infrastructure like secret management, telemetry tracking, project templates
✔ **Centralized**: single point of truth where repeated functionality is maintained and tested
✔ **Best practices**: secure and tracked by-default for every Arcus component

**Comment by stijnmoreels** [comment]
I'll check with @Mcalewaert and Erwin how we can add this to our site. We'll probably first move the current general site to a Docusaurus page.

**Comment by stijnmoreels** [comment]
Any other suggestions here? 
@fgheysels @pim-simons @ALaks96 @Dirk-Luyckx

**Comment by pim-simons** [comment]
No further suggestions from my side

**Comment by stijnmoreels** [comment]
Let's see what the meeting on March 25 will result into.

**Comment by stijnmoreels** [comment]
Was handled in #204
