### ISSUE TITLE
Dependency Upgrades in Microsoft.Extensions

### ISSUE THREAD

**Issue by gverstraete** [arcus-azure/arcus#186]
There are many packages delivered by Arcus which have on the Nuget dependency list Microsoft.Extensions to be lower than 5.

But as it turns out, the v6 versions of the packages still support .NETStandard 2.1.
Example: 
https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions/6.0.0

Could this be looked at and be upgraded?

+ As a follow up: do we have the possibility to automate this process?

**Comment by fgheysels** [comment]
Either way, I also think that the upper bound version in the range must be defined as a wildcard (at least for minor & patch nrs)

**Comment by gverstraete** [comment]
The thing is that Microsoft Extensions support .NET Standard 2.0 AND .net 6. so there is no reason (I think) why Arcus should not allow us to use these newer packages from Microsoft. As long as they support .netstandard2.0, Arcus his .netstandard2.0 should allow it.

**Comment by stijnmoreels** [comment]
@gverstraete , we discussed this problem offline and created an dedicated issue to fix these peculiar situation. #188 This will make sure that a .NET 6 project will get the lowest possible .NET 6 dependencies, instead of .NET Core dependencies. Hopefully this will help.

**Comment by stijnmoreels** [comment]
We can close this, I think, in favor of #188 .
