### ISSUE TITLE
Reference dependencies based on TargetFramework

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus#188]
**Is your feature request related to a problem? Please describe.**

We're currently targetting different .NET frameworks in Arcus libraries: .NET Core 3.x, .NET 6
This makes dependency management a bit hard.

**Describe the solution you'd like**
We should differentiate based on target framework which dependencies (and versions) we need to reference.  
This can be done by defining multiple ItemGroups with a condition applied to it.  
This means that we'll have an ItemGroup that defines the dependencies that are required for .NET Core 3.1 and an ItemGroup that defines the dependencies that are required for .NET 6 

In each ItemGroup, we must define the dependencies that are specific for that .NET target.

- For Guard.NET , we must use version 1.2 when targetting .NET Core 3.1, but use version 2.0 when targetting .NET 6
- For MS packages, we use versions with major version 3 when targetting .NET Core 3.1, but versions with major version 6 when targetting .NET 6

**Which version of the dependencies should we reference**
We should use the lowest version that is usable in Arcus per target framework.   
We shall not use wildcards.

This is related to #186

**Comment by fgheysels** [comment]
We should apply this change in this order:

- Arcus.Observability
- Arcus.Security
- Arcus.Messaging
- Arcus.WebApi
- Arcus.EventGrid
- ...

**Comment by stijnmoreels** [comment]
We could release ArcusTesting for internal use, but other than that, we only have to release the template projects for this to close.

**Comment by stijnmoreels** [comment]
> Templates have been released. Can this be closed @stijnmoreels or do we need to modify Testing ?

Ah, we could indeed release Arcus.Testing too, but this is a package we don't usually make very buzz about since it's mostly for (here it comes) testing 😄 .

**Comment by fgheysels** [comment]
Actually, I'm not even familiar with that package.  But we should release a new version of it if we can.

**Comment by stijnmoreels** [comment]
> Actually, I'm not even familiar with that package. But we should release a new version of it if we can.

Ok, done! So we can close this now! 🥳
