### ISSUE TITLE
Change the 'random' package reference in the GitHub release notes

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#198]
**Is your feature request related to a problem? Please describe.**
When having a single package or an `.All` package one can easily refer to this one in the GitHub release notes but if that isn't the case we can't just choose a 'random' package.

**Describe the solution you'd like**
Either list all the available packages in the GitHub release notes, or work with a general description as in: 
`Install a new version of the Arcus.Security package that you want via NuGet` or 

```shell
PM > Install-Package Arcus.Security.*
```

With a link to the search results of these packages.

- [x] Messaging
- [x] EventGrid
- [x] Security
- [x] Web API
- [x] Background Jobs
- [x] Templates
- [x] Testing
- [x] Observability
- [x] Scripting

**Additional context**
First mentioned here: https://github.com/arcus-azure/arcus.security/pull/339#discussion_r830349385

**Comment by fgheysels** [comment]
Or can we link to our documentation from there ?

**Comment by stijnmoreels** [comment]
Ah, yes, that is also an option. It would indeed not be very maintainable to list everything here. We can definitely add an link to the docs as well 👍 .
