### ISSUE TITLE
Provide tool for automating new repo setup

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus#2]
Provide tool for automating new repo setup.

This should create the following aspects in the GitHub repo:
- Default milestones
- Default labels
- Default issues

Following topics should be done as well:
- [x] Provide documentation
- [x] Provide CI

**Describe the solution you'd like**
We can use [octokit.net](https://github.com/octokit/octokit.net) for this.

**Comment by samneirinck** [comment]
Would it make sense to make it a powershell/bash script instead, so I don't have to compile a tool to create a new repo?

**Comment by tomkerkhove** [comment]
They don't really have any of those supported - [lib list].
But I'm open for suggestions!

**Comment by tomkerkhove** [comment]
Documentation is available at : https://github.com/arcus-azure/arcus/blob/master/tools/github-repo-configurator/README.md
