### ISSUE TITLE
Package version ranges cause problems

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus#221]
The version ranges that are specified on package dependencies cause problems when you're experimenting with (MyGet) preview versions

![image](https://user-images.githubusercontent.com/3605786/168899324-ed833ff9-cb79-4591-ac55-04e92febce2c.png)

**Comment by stijnmoreels** [comment]
We could maybe rethink our preview versions we give to the MyGet preview. If we take into account the recently released version as major, we wouldn't be having this problem.

**Comment by fgheysels** [comment]
You mean change the versioning strategy of the preview builds ?

Another solution might be to remove the the 'to' boundary in the version limit.

**Comment by stijnmoreels** [comment]
> You mean change the versioning strategy of the preview builds ?

Yes, that's right. We already changed this a bit to be compatible with other MyGet packages, but we could improve it a bit more to be more compatible with combinations of Arcus packages. Seems like the logical step forward. Is the kind of problem that doesn't occur in the beginning but will bubble up you have many different versions on different libraries.

 > Another solution might be to remove the the 'to' boundary in the version limit.

That would be a step backwards because we have added the 'to' boundary to fix the development problem when people combine different NuGet Arcus versions (already discussed this). Conclusion was: it's safer for both us as maintainers as consumers, and will help to manager better breaking changes.

**Comment by fgheysels** [comment]
Then we should go for changing the versioning strategy for MyGet packages.
I guess the idea would be that preview builds that will end up in MyGet will have at least the same major version-number as the current release ? Maybe the minor version can be the same to, and the patch can be an arbitrary number + suffix with preview and maybe a date  ?  Or how do you see that ?

(IDK if we would be able to automatically determine the versionnumber of the current release).

**Comment by stijnmoreels** [comment]
> I guess the idea would be that preview builds that will end up in MyGet will have at least the same major version-number as the current release ? Maybe the minor version can be the same to, and the patch can be an arbitrary number + suffix with preview and maybe a date ? Or how do you see that ?

Yes, something like that. We could do that and make the build number the patch number, or something like that. We could maybe even take in the entire version and make it a preview like `v1.2.3-preview456` where the `456` is the additional one on the current release.

**Comment by stijnmoreels** [comment]
> That would also work. I just wonder how you're going to retrieve the current release number ?

Remember that we did already something like this before. Like, extracting the version number from the NuGet API site, or something. We'll find a way. 😉

**Comment by fgheysels** [comment]
Sounds good :)

So to conclude, we can agree on assigning version-numbers to MyGet packages that look like this:

`<latest-official-released-versionnr>-preview<builddate.version>-PR-<prnr>`

For instance: `2.4.0-preview20220519.01-PR-101`   

(I dediced to add the PR number as well that triggered the build, since we have this now as well)

**Comment by stijnmoreels** [comment]
> Sounds good :)
> 
> So to conclude, we can agree on assigning version-numbers to MyGet packages that look like this:
> 
> `<latest-official-released-versionnr>-preview<builddate.version>-PR-<prnr>`
> 
> For instance: `2.4.0-preview20220519.01-PR-101`
> 
> (I dediced to add the PR number as well that triggered the build, since we have this now as well)

Yes, that's ok 👍 .

**Comment by stijnmoreels** [comment]
Hmm, seems that we already do this for forks: https://dev.azure.com/codit/Arcus/_build/results?buildId=61450&view=logs&j=143eea66-4597-539b-c2e7-6e457837a569&t=f511a6c3-5b66-546e-176f-788009de3038&l=12

And when I look at the Azure DevOps templates we use, then it's indeed already doing it for forks. So we're covered there. Seems like the scheduled CI builds are not using that, though.

**Comment by fgheysels** [comment]
I suggest we have a short meeting on this :)

**Comment by stijnmoreels** [comment]
> I suggest we have a short meeting on this (next week) :)

Oh, it's not a big deal, though, we can use `<last-officlal-released-version>-preview-<builddate.version>` in those cases of 'changed master' builds and scheduled builds, right?
