### ISSUE TITLE
Website navigation needs improvement

### ISSUE THREAD

**Issue by rjmarques01** [arcus-azure/arcus#241]
**Is your feature request related to a problem? Please describe.**
Today when we navigate to Arcus website, we do have some general information and links to the respective GitHub projects. From the GitHub projects we do have links for the documentation, so...

main site > github repo > documentation site

This sort of navigation seems a bit off and makes the documentation usage more difficult. On top of that is not possible to navigate from the documentation to any other module.

**Describe the solution you'd like**
I would propose that there would be a "single" site where it would have the general Arcus information together with each module download\installation instructions and documentation, in a way that it would be possible to navigate between them.

**Comment by fgheysels** [comment]
Hi Ricardo,

I think you have a valid point.  It would be helpful if you could easily navigate between modules.  However, I think this is due to the fact that the documentation is kept in Github per module, and build per module.

Maybe it would be an idea to have a link from the main site to the module-specific documentation site, bypassing the github repo link.  I'm not a front-end developer but I know it is not a good practice to use iframe's, but maybe there's another way to show the documentation-site 'embedded' in the main site.

@Mcalewaert  @stijnmoreels

**Comment by rjmarques01** [comment]
I don't know the details of how the documentation is generated in order to propose a solution, but simply from a user standpoint, without the technicalities what it would make sense to me it would be:

- single site explaining the Arcus, updates and release notes, how to install/download and usage documentation (with link to the github repo)
- github repos for source code and collaboration only

**Comment by stijnmoreels** [comment]
> github repos for source code and collaboration only

If we would remove the docs from the repositories, then every code contribution would have to be two PR's: 1 for the source code change to the target repository, and one to the general repository. Releasing of a new version would also be more complex and permissions (of even contributors who don't have rights now on the general repo) would be able to access documentation of repositories for which they aren't contributor. Both the contributions of code-owners and Codit contributors would become harder to track, too. Right know, a single contribution to a repo contains everything: source code, tests, build pipeline, and documentation. This allows faster and more correct development and review. Removing that, would make the documentation even harder to maintain.
What we could do, but don't know if that's possible, is to download all the documentation files during the building of the general site, and maybe then we could show it all on the same place, but still have it separate in each repository.

**Comment by pim-simons** [comment]
Maybe we are overthinking this, the initial issue from @rjmarques01 was this:
>main site > github repo > documentation site
>
>This sort of navigation seems a bit off...

If we are on the [main site](https://arcus-azure.net/) and I want to see the documentation on Observability I am directed [here](https://github.com/arcus-azure/arcus.observability), then I need to click on the link in the top right of the GitHub page so I am directed to the actual documentation [here](https://observability.arcus-azure.net/).

Wouldn't it be a lot simpler of we skip the middle step of the GitHub page. So if you click from the main site on one of the components you are directed to the documentation website of that component, for example https://observability.arcus-azure.net. 

That would make a lot more sense to me actually.

**Comment by stijnmoreels** [comment]
Yes, that's true. And you'll see that the preview site skips this: https://arcus-website.vercel.app/components , so on that part, we are already done 👍

**Comment by pim-simons** [comment]
> Yes, that's true. And you'll see that the preview site skips this: [arcus-website.vercel.app/components](https://arcus-website.vercel.app/components) , so on that part, we are already done 👍

Ah you are right, much better 👍🏻

**Comment by stijnmoreels** [comment]
@rjmarques01 did you already take a look at our new site?
➡️ https://arcus-azure.net/ 
It provides much more and structured information about Arcus and has direct references to the documentation site and GitHub page of each component.

I'll close this issue, but feel free to re-open or create a new one if you experience any problems. 👍
