### ISSUE TITLE
Naming - Do we suffix async methods with Async?

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus#28]
Some people prefer to suffix async methods with `Async` while others don't.

At the beginning of Arcus we chose to go the non-prefix route but recently this came up again.

What do you prefer? Why?

Depending on the outcome we can determine if we should change it, but that would mean we have a breaking change on our public API.

**Comment by tomkerkhove** [comment]
Paging @SamVanhoutte 	@fgheysels 	@stijnmoreels

**Comment by fgheysels** [comment]
I'm in favor of suffixing async methods with `Async`.
Why:
- It's inline with the .NET api's
- It's instantly clear for a developer that the method is async and can be awaited, so it reduces the risk of calling that method without awaiting it (where you do this in most of the cases), and have unexpected results.

It is offcourse a drawback if this means that there will be breaking changes, but they can maybe be avoided by keeping the existing methods around for a while and marking them with an `Obsolete` attribute stating that the developer should use the new 'async suffixed' version of that method.  Advantage of this way of working is that you can gradually shift to the newly named methods

```csharp
[Obsolete("Use DoSomethingAsync instead")]
public async Task DoSomething() {}

public async Task DoSomethingAsync() {}
````

**Comment by tomkerkhove** [comment]
I fully agree. Let's make it happen - Will create required issues asap.

**Comment by tomkerkhove** [comment]
In terms of interfaces, I'm open for suggestions where we can just add them (breaking) or introduce a new interface, but that means we need to change some other stuff to use the new interfaces.

What approach would you use?

Any volunteers to introduce some coding guidelines in this repo instead of Azure DevOps?

**Comment by stijnmoreels** [comment]
I think this is done?
