### ISSUE TITLE
[Blog] W3C service-to-service correlation summary

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#295]
**Describe the post outline you'd like**
Explain how the most recent Arcus releases provide W3C support and how you can migrate towards it.

**Comment by rjmarques01** [comment]
It would be interesting that you could show the how (visually) it looks like with Arcus, versus without, to better understand the added value.

**Comment by stijnmoreels** [comment]
> It would be interesting that you could show the how (visually) it looks like with Arcus, versus without, to better understand the added value.

The blog here is mostly how W3C vs Hierarchical. To have a full visual walkthrough, there would the [user guides](https://observability.arcus-azure.net/Guidance/Service-to-service%20Correlation/index) by most helpful.

**Comment by stijnmoreels** [comment]
Also note that with Arcus, the service-to-service correlation will not be that different from a system that solely uses Microsoft technology. The main difference that Arcus brings is that the nifty, complex correlation is hidden from the application code and is easily accessible via accessors registered in the application's dependency container. You can't have that with solely using Arcus.
