### ISSUE TITLE
.NET 8 support

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus#311]
The first preview of .NET 8 has been released.

Might be a good idea to start looking at it and what the impact on the arcus libs is.

https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/

Release preview version with .NET 8 support:
- [x] Observability
    - [x] Everything set, release major version (https://github.com/arcus-azure/arcus.observability/releases/tag/v3.0.0)
- [x] Security
    - [x] Add .NET 8 support w/ Arcus Observability preview 
    - [x] https://github.com/arcus-azure/arcus.security/issues/202
    - [x] https://github.com/arcus-azure/arcus.security/issues/304
    - [x] https://github.com/arcus-azure/arcus.security/issues/305
    - [x] https://github.com/arcus-azure/arcus.security/issues/306
    - [x] https://github.com/arcus-azure/arcus.security/issues/325
    - [x] https://github.com/arcus-azure/arcus.security/issues/329
    - [x] https://github.com/arcus-azure/arcus.security/issues/311
    - [x] https://github.com/arcus-azure/arcus.security/issues/311
    - [x] https://github.com/arcus-azure/arcus.security/issues/259
    - [x] Use new major Arcus Observability package w/ .NET 8 support (https://github.com/arcus-azure/arcus.security/pull/427)
    - [x] Everything set, release major version (https://github.com/arcus-azure/arcus.security/releases/tag/v2.0.0)
- [x] Web API
    - [x] Add .NET 8 support w/ Arcus Observability + Security preview https://github.com/arcus-azure/arcus.webapi/pull/455
    - [x] https://github.com/arcus-azure/arcus.webapi/pull/442
    - [x] Use new major Arcus Observability + Security package w/ .NET 8 support
    - [x] Everything set, release major version (https://github.com/arcus-azure/arcus.webapi/releases/tag/v2.0.0)
- [x] Messaging
    - [x] https://github.com/arcus-azure/arcus.messaging/pull/427
    - [x] https://github.com/arcus-azure/arcus.messaging/pull/428
    - [x] https://github.com/arcus-azure/arcus.messaging/issues/234
    - [x] https://github.com/arcus-azure/arcus.messaging/issues/235
    - [x] https://github.com/arcus-azure/arcus.messaging/issues/236
    - [x] https://github.com/arcus-azure/arcus.messaging/issues/252
    - [x] https://github.com/arcus-azure/arcus.messaging/issues/296
    - [x] https://github.com/arcus-azure/arcus.messaging/issues/297
    - [x] https://github.com/arcus-azure/arcus.messaging/issues/300
    - [x] https://github.com/arcus-azure/arcus.messaging/issues/305
    - [x] https://github.com/arcus-azure/arcus.messaging/issues/387
    - [x] Use new major Arcus Observability + Security packages w/ .NET 8 support
    - [x] Everything set, release major version (https://github.com/arcus-azure/arcus.messaging/releases/tag/v2.0.0)
- [x] Event Grid
    - [x] Awaiting discussion on usability... 
- [x] Background Jobs
    - [x] https://github.com/arcus-azure/arcus.backgroundjobs/issues/112
    - [x] https://github.com/arcus-azure/arcus.backgroundjobs/issues/149
    - [x] https://github.com/arcus-azure/arcus.backgroundjobs/issues/150
    - [x] Use new major Arcus Messaging package w/ .NET 8 support
    - [x] Everything set, release major version
- [x] Templates
    - [x] https://github.com/arcus-azure/arcus.templates/issues/807
    - [x] Use new major Arcus Web API + Messaging packages w/ .NET 8 support (https://github.com/arcus-azure/arcus.templates/pull/873)
    - [x] Everything set, release major version
- [x] Testing
    - [x] Mostly for internal use, currently skipping. If the test projects need it, we can update this one, too.

**Comment by stijnmoreels** [comment]
- [ ] Write-up relationship between Arcus components so that we know in which order we have to update the repositories towards new .NET versions.

**Comment by fgheysels** [comment]
.NET 8 is currently in a pre-release state, so I think it is a good time to start preparing supporting .NET 8 :)

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8

**Comment by stijnmoreels** [comment]
Great, but is there anything we can do before it releases?

**Comment by fgheysels** [comment]
I would say that we could:

- install the latest preview version of .NET 8
- start making changes on the multiple Arcus components to support .NET 8 using that preview version.   

That should give use a head-start as I don't expect that there will be fundamental changes between these recent preview version and the final version (which is due to be released in november 2023).
That should give us the possiblity to prepare everything already now, and release a version of Arcus that supports .NET 8 just a few days after the official .NET 8 release.

**Comment by fgheysels** [comment]
.NET 8 is currently officially released, so we can make sure that all docker-files in test projects and all Arcus template files refer to an officially released .NET 8 version

**Comment by fgheysels** [comment]
Can we close this one ?

**Comment by fgheysels** [comment]
This has been done.

**Comment by stijnmoreels** [comment]
Yes, indeed, all done 🥳
