### ISSUE TITLE
Implement linters to enforce code-styles

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus#323]
It would be a good idea if we, as part of our build and validation process, have an automated way to verify if code complies to some coding guidelines and conventions.

I'm thinking about checking unnecessary whitespace, order of constructors / properties, etc...

**Comment by stijnmoreels** [comment]
We already have something like that with Codefactor https://github.com/organizations/arcus-azure/settings/installations/9512724 . It will check whitespace and other stuff. The order of things, that is probably not checked.
