### ISSUE TITLE
Archive Arcus repositories that are not active anymore

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus#363]
Certain Arcus repositories are no longer actively being maintained.
Others have no real added value anymore.

These repositories should be archived / moved to the public archive.

These repositories can be archived:

- [Arcus ML](https://github.com/arcus-azure/arcus.ml)
- [Arcus Azure ML](https://github.com/arcus-azure/arcus.azureml)
- [Arcus EventGrid](https://github.com/arcus-azure/arcus.eventgrid)

**Comment by stijnmoreels** [comment]
Done 👍
