### ISSUE TITLE
Archive Arcus.BackgroundJobs

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus#364]
The [Arcus.BackgroundJobs](https://github.com/arcus-azure/arcus.backgroundjobs) was once created as a repository that would contain some useful background-jobs for Azure components.

Although the concept is worthy and the repo contains some nice features, this is actually out-of-scope of the Arcus library, which is a development library which assists developers in applying best-practices in their own code / applications that runs on Azure.
Therefore, we will no longer support and archive the Arcus.BackgroundJobs repository.   The backgroundjobs that are present in this repo can maybe be moved towards the Codit practices.

**Comment by stijnmoreels** [comment]
@pim-simons , can you confirm this that this applies to all jobs described in the repo?

**Comment by pim-simons** [comment]
Will go through all backgroundjobs available at the moment and see what we can move, will get back to you on that.

**Comment by pim-simons** [comment]
To get back to this, I think we can move the [Check Applications in Azure Active Directory for potential expired client secrets](https://background-jobs.arcus-azure.net/Features/AzureActiveDirectory/client-secret-expiration-job) to the [platform operations practice](https://github.com/Codit/platform-operations-practice)], the other ones I am not so sure about as I don't really have experience with them. I also don't really see a need for one of the other ones on the projects I am working at, but that might just be me as I am working on mostly integration projects. 

Also, I guess we are only archiving the backgroundjobs repo right? So if we find that we need any of the jobs in this repo on a project we can just move it then.

**Comment by fgheysels** [comment]
Yes, it'll just be archived.

**Comment by pim-simons** [comment]
> Yes, it'll just be archived.

In that case no objections from me to go ahead with archiving 👍🏻

**Comment by stijnmoreels** [comment]
Done https://github.com/arcus-azure/arcus.backgroundjobs 👍
