### ISSUE TITLE
Enhance exception handling in RepositoryTool

### ISSUE THREAD

**Issue by SamVanhoutte** [arcus-azure/arcus#57]
**Describe the bug**
When incorrect repository is passed in the arguments, the program throws an exception with a placeholder : `Repository {repositoryName} was not found'.  

**To Reproduce**
Run tool with incorrect repo name

**Expected behavior**
Repo name should be included in exception and user should be guided on correct use

**Comment by tomkerkhove** [comment]
Done via #60
