### ISSUE TITLE
Provide versioned documentation on all repos

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus#75]
Provide versioned documentation on all repos

**Comment by stijnmoreels** [comment]
+ we could/should create some action that does the following on each new release:

Create a new PR on the repo with the following changes:
- Copy `./docs/features/**` & `./docs/index.md` to new folder `./docs/vx.x.x` 
- Copy `./docs/preview/features/**` to `./docs/features/**` (overwrite)
- Copy `./docs/preview/index.md` to `./docs/index.md` (overwrite)

In the created PR, we could then add some additional NuGet or other badges manually if not already done.

**Comment by tomkerkhove** [comment]
This GitHub Action can help when a new tag (== release) is created - https://github.com/marketplace/actions/create-pull-request

**Comment by stijnmoreels** [comment]
Closing in favor of #86 and bc this issue's work is done.
