### ISSUE TITLE
Running GitHub repository configurator fails with 'not found' message exception

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#80]
**Describe the bug**
When running the tool, the Octokit GitHub client receives following response:
```json
{
    "message":"Not Found",
    "documentation_url":"https://developer.github.com/v3/issues/milestones/#create-a-milestone"
}
```

**To Reproduce**
* Create dummy repo with arcus template
* Run the configuration tool on the dummy repo

**Expected behavior**
The milestones and issues should be added.

**Additional context**
There's a new GitHub API version (v4) but no new Octokit NuGet version to interact with this new API.

**Comment by tomkerkhove** [comment]
Don't they support the previous API version anymore? I presume the user has required permissions?

**Comment by stijnmoreels** [comment]
I used the arcus automation user. So I figured it would be allowed. But you're right I should have checked that.
I added them manually now.

**Comment by tomkerkhove** [comment]
Let me know if it helps

**Comment by stijnmoreels** [comment]
Yes, that helps :trollface: . Sorry for this.
