### ISSUE TITLE
Q: can we set the issues+milestones already in the GitHub repository template?

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#81]
Quick question: we have a tool to configure the issues+milestones in new projects, but just like the lables that are already in the GitHub repository template (and are moved correctly to new GitHub repositories), can we already setup the issues+milestones in that repository template instead of running it on every new repository?

**Comment by tomkerkhove** [comment]
Nope, unfortunately not - AFAIK only content from the Git repo is supported.

Because of that I've already set a bunch of default labels on the org which take them over by default.
