### ISSUE TITLE
Feature docs in repo's are not browsable inside the repo itself

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#85]
**Is your feature request related to a problem? Please describe.**
Currently, we only support paths in the links between different doc pages, so the file extension (`.md`) is not included.
This means that we cannot navigate inside the repo itself to different files.

**Describe the solution you'd like**
Is there a possibility to make this supported in both ways (on site and in repo)?

**Additional context**
Initial question came from @SamVanhoutte .

**Comment by stijnmoreels** [comment]
Thanks @SamVanhoutte for the question/consideration. 👊

**Comment by stijnmoreels** [comment]
@tomkerkhove , not sure if this can be done with the current setup of the Jekyll docs generation.
We, for one don't use the actual file extension when referencing the different pages.
Is there a way arround this in Jekyll?

**Comment by tomkerkhove** [comment]
HOnestly I don't know so we would have to investigate

**Comment by tomkerkhove** [comment]
Closing since it's been open for a while and we are changing our doc approach
