### ISSUE TITLE
Migrate all Azure DevOps pipelines to Parameter concept

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus#88]
**Is your feature request related to a problem? Please describe.**
Migrate all Azure DevOps pipelines to Parameter concept instead of adding a commented variable name ([example](https://github.com/arcus-azure/arcus.security/blob/master/build/nuget-release.yml#L18))

YAML spec: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#parameters

**Describe the solution you'd like**
This allows us to bring the configuration options for triggering a pipeline to our YAML definition and consuming them as we want instead of having to comment them and hope they are still in line.

Another added value is that it allows you to be more strict on the expected values by defining a list of values that is allowed (such as Full/Prerelease) if we want to.

**Additional context**
You can find an example here: https://github.com/tomkerkhove/promitor/blob/master/build/azure-devops/agents-scraper-release-official.yml#L7

**Comment by stijnmoreels** [comment]
Done I think?

**Comment by tomkerkhove** [comment]
Done for Arcus but would be good to apply it there as well
