### ISSUE TITLE
Create GitHub draft releases with predefined release notes structure

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#89]
**Is your feature request related to a problem? Please describe.**
Currently, when releasing a full release in the repo's; we manually edit the already published release and provide some additional titels to explain the changes in the current release.

**Describe the solution you'd like**
We could change this approach by releasing our GitHub releases as _draft_ releases with the predefined titles but without any description just yet. We then can manuallly 'publish' the release with the added descriptions.

**Additional context**
* [GitHub release task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops)
* Additional titles in the release:

```markdown
## What's new?
### Features

- 

### Fixes / Changes
None.

### Breaking Changes
None.

### Removal
None.
```

**Comment by tomkerkhove** [comment]
Example of draft flag: https://github.com/tomkerkhove/promitor/blob/master/build/azure-devops/agents-scraper-release-official.yml#L233
