### ISSUE TITLE
Target the 'lowest' framework that is possible

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus#93]
I've seen that some Arcus libraries are targetting multiple platforms, like .NETCore3.1 and netstandard 2.0.

For intance:

- Arcus.Security is targetting netstandard2.0 and netcoreapp3.1
- Arcus.Messaging projects is targetting netstandard2.0 and netcoreapp3.1
etc...

I think that, as long as the Arcus library has no dependencies on .NET Core libraries, it should be sufficient for the Arcus library to only target netstandard2.0,   (netstandard2.0 can be used by .NET Core 3.x as well).

![image](https://user-images.githubusercontent.com/3605786/93990359-4fd71a80-fd8b-11ea-9e82-1c5895b75295.png)

Source: https://dotnet.microsoft.com/platform/dotnet-standard

Only those libraries that have dependencies to .NET Core 3.x libs should have multiple target frameworks.  (I think Arcus.WebApi should for instance, but I'm not sure).

**Comment by tomkerkhove** [comment]
@fgheysels Added link to the website in the issue.

This is fine for me, @stijnmoreels can you please take a look at this for all our components please?

**Comment by stijnmoreels** [comment]
Hmm, that reminds me of an earlier issue we had. Originally, we had everything only on `netstandard` but we changed that to both `netstandard` and `netcoreapp` because you had problems with your projects? It's strange to now go back to the way it was?

**Comment by fgheysels** [comment]
I think it was an issue with the arcus.webapi package, where -I think- we need to target them both.

**Comment by stijnmoreels** [comment]
Yes, that was it. Are we now saying that that migration was wrong? And if so, should it be reversed?

**Comment by fgheysels** [comment]
No, the migration was not wrong.
The reasoning goes like this:

For Arcus.WebApi, we needed to make this distinction, since the version of Arcus.WebApi that targets `netstandard2.0` referencees some ASP.NET Core packages.   However, when we have an ASP.NET Core project that targets .NET Core 3.X, and references Arcus.WebApi, we had a (transitive) package reference to `Microsoft.AspNetCore.Mvc.Core` which is not compatible with what is required by the ASP.NET Core 3.x project.    (ASP.NET Core 3.x projects use the Microsoft.AspNetCore.App framework which is not compatible with Microsoft.AspNetCore.* packages as far as I remember).

By making sure that Arcus.WebApi targets both `netstandard2.0` and `netcoreapp3.0`, that issue has been resolved.  In the version that targets `netstandard2.0` we include the reference to those required Microsoft.AspNetCore packages.  When targetting `netcoreapp3.0` we make sure that those packages are not included.   Then, when an ASP.NET Core project references ARcus.WebApi, the correct version of Arcus.WebApi is used.

**Comment by fgheysels** [comment]
A thing that is more important, is that we make sure that we do not include unnecessary packages in all Arcus libraries, like it was the case in Arcus.Security.  (https://github.com/arcus-azure/arcus.security/pull/190)

**Comment by stijnmoreels** [comment]
> So, for Arcus.WebApi, that approach is certainly valid. I don't know however if the same is true for the other Arcus libraries. (For Arcus.Security for instance, I think it is sufficient to only target .netstandard2.0. (Although it is not wrong to target both .netstandard and .netcoreapp, but it is imo not necessary / required).

Well, we have run through all the Arcus libraries and everywhere there was a reference to a `Microsoft.Extensions.*` package, we've chosen to this approach of using this double target framework approach. But if I read it now correctly, that isn't correct anymore? So, to conclude, we should use `Microsoft.Extensions.*` packages but above v3? instead of using a double target framework?

**Comment by stijnmoreels** [comment]
I also have a question on this PR on the security repo. Does that means that we're not supporting .NET Core 2.2 anymore? I guess the reason why split this was that we support both but I see that we now move to a higher NuGet package version 3.* that isn't supported in .NET Core 2.2 anymore?

Plus, I'm curious though, how we should update the remaining projects. Some of them have still references to `Microsoft.Extensions.*` packages but if I'm reading it correctly, we should just update them and remove the conditionals on the target frameworks?

**Comment by fgheysels** [comment]
I think it is a tough subject :)

There are 2 things imho:

- IMO, it is not wrong to target both .netstandard2.0 and .netcoreapp3.0.  Actually, it seems like some Microsoft package are doing this as well, even though there are no differences in both targets:

![image](https://user-images.githubusercontent.com/3605786/94822223-b353ee80-0402-11eb-8e35-814d088e2602.png)

So for me, we can leave it as is.  It might be easier in the future to support if there will be differences in dependencies between the 2 versions (like we have in arcus-webapi).

- We should definitely not reference Microsoft.AspNetCore.App in projects that do not require it.  (Arcus.Security had a reference to it, but it actually has no dependency on it.  By having the reference, using Arcus.Security in a container which did not contain the asp.net framework failed).  I dont know if there are any other Arcus projects that are referencing the AspNetCore.App framework but do not require it.

**Comment by tomkerkhove** [comment]
> * We should definitely not reference Microsoft.AspNetCore.App in projects that do not require it.  (Arcus.Security had a reference to it, but it actually has no dependency on it.  By having the reference, using Arcus.Security in a container which did not contain the asp.net framework failed).  I dont know if there are any other Arcus projects that are referencing the AspNetCore.App framework but do not require it.

This is definitely true, AFAIK we should only have this in Web API or templates for Web API template, can you verify this please @stijnmoreels ?

**Comment by tomkerkhove** [comment]
> * IMO, it is not wrong to target both .netstandard2.0 and .netcoreapp3.0.  Actually, it seems like some Microsoft package are doing this as well, even though there are no differences in both targets:
> 
> ![image](https://user-images.githubusercontent.com/3605786/94822223-b353ee80-0402-11eb-8e35-814d088e2602.png)
> 
> So for me, we can leave it as is. It might be easier in the future to support if there will be differences in dependencies between the 2 versions (like we have in arcus-webapi).

If we can target .netstandard2.0 and it's safe to remove .netcoreapp3.0 then I would do this indeed. Less things to worry about and apparently .netcoreapp3.0 implements .netstandard2.0 based on the image.

> I also have a question on this PR on the security repo. Does that means that we're not supporting .NET Core 2.2 anymore? I guess the reason why split this was that we support both but I see that we now move to a higher NuGet package version 3.* that isn't supported in .NET Core 2.2 anymore?

Actually no @stijnmoreels, as you can see .netstandard2.0 is implemented by both .netcoreapp2.2 & .netcoreapp3.0 

![Overview](https://user-images.githubusercontent.com/3605786/93990359-4fd71a80-fd8b-11ea-9e82-1c5895b75295.png)

*Source: [dotnet.microsoft.com/platform/dotnet-standard](dotnet.microsoft.com/platform/dotnet-standard)*

However, will that mean we will never have issues between both? No, it can happen, but only then we should explicitly target 3.0 (or 5.0 in the future).

That's my understanding at least, right @fgheysels ?

**Comment by fgheysels** [comment]
That would be my understanding as well @tomkerkhove

**Comment by tomkerkhove** [comment]
I think this can be closed, right @fgheysels ?

**Comment by fgheysels** [comment]
Yes, closed.
