### ISSUE TITLE
Q: should we make it a habbit to update the dependent packages on new major versions?

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus#96]
**Is your feature request related to a problem? Please describe.**
Several times now, we have people asking us to update dependency packages bc we would still use an 'old' one.

**Describe the solution you'd like**
Maybe we should also have an issue on each milestone that indicates to update the dependency packages (in case of a major, updates to new major version, in case of a minor, update until new minor version).

**Describe alternatives you've considered**
Other package management strategies could be considered also, of course. Only update in case of a major for example.

**Comment by tomkerkhove** [comment]
I'd prefer to keep the major dependencies as low as possible as it forces certain version on people:
![image](https://user-images.githubusercontent.com/4345663/97164252-24788e80-1782-11eb-8819-095a13b188ce.png)

The higher we go, the more we force people to move to cutting-edge versions. The only exceptions should be, imo, when a dependency we use has security vulnerabilities and/or bugs which we suffer from.
