### ISSUE TITLE
[Blog] Write blog post on how to use Arcus Background Jobs to gain insights in Databricks jobs

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus#98]
**What is the goal of the blog post**
Walk through the process of monitoring Databricks jobs with Arcus Background Jobs to show how you can use Azure Monitor alerts on those metrics; which is not possible out-of-the-box.

**Describe the post outline you'd like**

- Problem - Azure Databricks doesn't provide job metrics out-of-the-box
- Walkthrough
  - Show cluster jobs which are failing
  - Use Azure Functions with our module and get it up and running for that cluster
  - Run Function and trigger some jobs
  - Show generated metrics in dashboard and how to create alert for it
- Extend, not re-invent
  - Emphasize that we're not re-inventing the wheel but extending by using the official SDK
- Roadmap
  - Arcus Template is coming (https://github.com/arcus-azure/arcus.templates/issues/246)

**How do you think this will help?**
Provide operable Databricks jobs.

**Comment by tomkerkhove** [comment]
@SamVanhoutte Is this something you'd like to review?

**Comment by stijnmoreels** [comment]
Some concepts here are not really things that I'm familiar with: 'failing cluster jobs'? Not sure how to generate these metrics too?

**Comment by tomkerkhove** [comment]
Oh with that I meant just a job that runs on the cluster that has failed, does this clarify things?

**Comment by stijnmoreels** [comment]
And can we generate something like that? I'm not so familiar with Databricks and the jobs that run there.

**Comment by tomkerkhove** [comment]
Just like how we do in our integration testing I presume - We trigger a job on Databricks and let it fail :)

**Comment by SamVanhoutte** [comment]
> @SamVanhoutte Is this something you'd like to review?

I think it might be good to ask @gverstraete or @SriramAvatar for their input or help

**Comment by gverstraete** [comment]
Not sure what is expected from me here. But if you want to test it, yes, the easiest way seems to me to let a databricks job fail/succeed.. 
But Sam his mention was at the time you weren't discussing that. So if you would like me to review the blog post. Sure! no problem.

**Comment by tomkerkhove** [comment]
Reviewing the post would be a big help if you want @gverstraete once it's ready

**Comment by tomkerkhove** [comment]
This is just pending publishing, right @stijnmoreels ?

**Comment by stijnmoreels** [comment]
> This is just pending publishing, right @stijnmoreels ?

Yep, already added to the CMS and waiting for Vanessa to review it.

**Comment by stijnmoreels** [comment]
Oh, and probably also adding a blogpost file to this repo so it's shown on the Arcus site.

**Comment by stijnmoreels** [comment]
Published: https://www.codit.eu/blog/databricks-jobs-arcus-background-jobs/
